server:
    port: 16001
spring:
    application:
        name: gateway
    datasource:
        url: jdbc:mysql://47.98.104.98:3306/shop?useSSL=false&serverTimezone=UTC&characterEncoding=utf8
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: root
        password: jxZ03121994!
        hikari:
            idle-timeout: 600000
            max-lifetime: 1800000
            maximum-pool-size: 10
            minimum-idle: 10
    cloud:
        nacos:
            server-addr: http://101.34.207.33:12222
            username: nacos
            password: Rtt0312*
            discovery:
                namespace: dev
                group: shop
                enabled: true
        gateway:
            enabled: true
            loadbalancer:
                use404: true
            globalcors:
                add-to-simple-url-handler-mapping: true
                cors-configurations:
                    '[/**]':
                        allowedOrigins: "*"
                        allowed-methods: "*"
            discovery:
                locator:
                    enabled: true
                    lower-case-service-id: true
            httpclient:
                connect-timeout: 1000
                response-timeout: 5s